# Generated by Django 4.2.4 on 2023-09-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="url",
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
